spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nk-blog
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

nkblog:
  app:
    jwtSecret: nkSecretKey
    jwtExpirationMs: 86400000